openapi: 3.0.1
info:
  title: Medical Code API
  description: API for managing and uploading medical codes.
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.org

servers:
  - url: /api/medical-records

paths:
  /upload:
    post:
      summary: Upload a CSV file with medical codes
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "200":
          description: CSV file uploaded and processed successfully
          content:
            application/json:
              schema:
                type: string
        "400":
          description: Error processing file
          content:
            application/json:
              schema:
                type: string

  /:
    get:
      summary: Get all medical codes
      responses:
        "200":
          description: A list of medical codes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MedicalRecord'

    delete:
      summary: Delete all medical codes
      responses:
        "200":
          description: All medical codes deleted successfully
          content:
            application/json:
              schema:
                type: string

  /{code}:
    get:
      summary: Get a medical code by code
      parameters:
        - in: path
          name: code
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Medical code found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MedicalRecord'
        "404":
          description: Medical code not found

components:
  schemas:
    MedicalRecord:
      type: object
      properties:
        id:
          type: integer
          format: int64
        source:
          type: string
        codeListCode:
          type: string
        code:
          type: string
          uniqueItems: true
        displayValue:
          type: string
        longDescription:
          type: string
        fromDate:
          type: string
          format: date
        toDate:
          type: string
          format: date
        sortingPriority:
          type: integer
          format: int32
